name: release

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        extension:
          - simply-extension-pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: npm

      - run: npm ci

      - run: npx semantic-release
        working-directory: extensions/${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
